name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: Windows, Linux, Mac    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.5.1' # Adjust based on your project's requirements

    - name: Install dependencies
      run: npm install

    - name: Deploy to VM
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key $SSH_USERNAME@$SSH_HOST "cd /path/to/your/app && git pull origin main && npm install && pm2 restart all"